USE [master]
GO

/****** Object:  Database [HRS]    Script Date: 12/13/2017 3:18:27 PM ******/
CREATE DATABASE [HRS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HRS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER1\MSSQL\DATA\HRS.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HRS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER1\MSSQL\DATA\HRS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HRS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HRS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HRS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HRS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HRS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HRS] SET ARITHABORT OFF 
GO

ALTER DATABASE [HRS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HRS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HRS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HRS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HRS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HRS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HRS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HRS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HRS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HRS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HRS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HRS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HRS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HRS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HRS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HRS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HRS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HRS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HRS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HRS] SET  MULTI_USER 
GO

ALTER DATABASE [HRS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HRS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HRS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HRS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HRS] SET  READ_WRITE 
GO

